---
title: "go-swaggerの【swagger generate】でハマった注意点 "
emoji: "⚠"
type: "tech" # tech: 技術記事 / idea: アイデア
topics: ["Swagger", "Go", "OpenAPI"]
published: true
---

## 経緯
業務で[go-swagger](https://goswagger.io/)を使用することとなり、Swaggerファイルを分割していくと方針が決まりました。
分割するに当たりSwaggerのディレクトリ構成は以下になりました。
```
├─swagger
│   ├──サブシステム
│   │  └───業務
│   │        └───画面
│   │              ├───paths.yaml(api定義)
│   │              ├───paths.yaml(api定義)
│   │              └───definitions.yaml(models定義)
│   │
│   ├──swagger.yaml
```
クライアントの画面ごとにapiを呼び出すため、上記のようなディレクトリ構成で管理していこうとなりました。
各画面ごとのapi定義とmodels定義をswagger.yamlで呼び込みます。

## ハマった点
```type: array```を```$ref```で呼び出す
Petというmodelを定義し、配列で呼び込もうとした場合
```yaml:definitions.yaml
Pet:
  type: "object"
  properties:
    id:
      type: "integer"
      format: "int64"
    name:
      type: "string"
      example: "doggie"
```
```yaml:pet.yaml
responses:
  200:
    description: "successful operation"
    schema:
      type: "array"
      items:
        $ref: "./definitions.yaml#/Pet"
```
```yaml:swagger.yaml
paths:
  /pet:
    $ref: ./sub_system/business/screen/pet.yaml
definitions:
  Pet:
    $ref: "./sub_system/business/screen/definitions.yaml#/Pet"
```

しかし上記の構成で```swagger generate server -t gen -f ./swagger/swagger.yaml```を実行すると。。。
```terminal
$ swagger generate server -t gen -f ./swagger/swagger.yaml
2022/02/05 02:41:15 validating spec /home/ubuntu/go/src/custom-server/swagger/swagger.yaml
2022/02/05 02:41:15 preprocessing spec with option:  minimal flattening
could not resolve schema: open /home/ubuntu/go/src/custom-server/swagger/definitions.yaml: no such file or directory
```
上記のようなエラーとなりgenerateに失敗します🙃
原因はわかりません。。
SwaggerViewerで確認しても問題ないし、Swagger Editorにも記載されている書き方とほぼ同じなのに。。

## 対応策
arrayのmodelを作成してそれを呼び込む
```diff yaml:definitions.yaml
+  PetList:
+    type: "array"
+    items:
+      $ref: "#/Pet"
Pet:
  type: "object"
  properties:
    id:
      type: "integer"
      format: "int64"
    name:
      type: "string"
      example: "doggie"
```
```diff yaml:pet.yaml
responses:
  200:
    description: "successful operation"
    schema:
-      type: "array"
-      items:
-        $ref: "./definitions.yaml#/Pet"
+      $ref: "./definitions.yaml#/PetList"
```
```diff yaml:swagger.yaml
paths:
  /pet:
    $ref: ./sub_system/business/screen/pet.yaml
definitions:
  Pet:
    $ref: "./sub_system/business/screen/definitions.yaml#/Pet"
  PetList:
+    $ref: "./sub_system/business/screen/definitions.yaml#/PetList"
```

上記だとgenerateに成功します👏

## 課題
分割していると```swagger generate```できても```swagger validate```でWARNINGが出現する😇
```terminal
$ swagger validate ./swagger/swagger.yaml
2022/02/05 03:02:41
The swagger spec at "./swagger/swagger.yaml" is valid against swagger specification 2.0
2022/02/05 03:02:41
The swagger spec at "./swagger/swagger.yaml" showed up some valid but possibly unwanted constructs.
2022/02/05 03:02:41 See warnings below:
2022/02/05 03:02:41 - WARNING: definition "#/definitions/PetList" is not used anywhere
2022/02/05 03:02:41 - WARNING: definition "#/definitions/Pet" is not used anywhere
```